# Generated by Django 4.0.3 on 2022-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='Zip Code'),
        ),
    ]
